### PR TITLE
StringNormalizer drops strings when they only contain stop words

### PR DESCRIPTION
**Pull request by xadupre**
Issue raised in https://github.com/microsoft/onnxruntime/issues/17795 and https://github.com/onnx/sklearn-onnx/issues/998. After investigation, operator StringNormalizer drops strings containing only stopwords. The expected output can be obtained by running the inference for every input independantly.

A possible fix would be to update onnx specifications to not drop strings. Another fix could be to update the converter and loop over rows but that's not very efficient.

### CODE REVIEW

**Comment by vsbaldeev** [comment]
@xadupre Hi! Any updates on this problem ?

As I understand the fast fix would be to process every string independently. RIght ?

**Comment by xadupre** [comment]
That would work.

**Comment by xadupre** [comment]
If you are using a loop, it is not really suprising. There is no parallelization even though each row is processed independently.

**Comment by vsbaldeev** [comment]
> If you are using a loop, it is not really suprising. There is no parallelization even though each row is processed independently.

May you suggest some impovement in this case ?

My guess is if I know indices of dropped strings then I can rerun inference session only on them instead loop over all input items.

**Comment by vsbaldeev** [comment]
Also I want to notice that I don't user stop_words parameter. How exactly set stop_words parameter to empty or None while converting to ONNX model ?

**Comment by xadupre** [comment]
One issue is StringNormalizer is defined in onnx. To change its behaviour, it has to be changed in onnx and onnxruntime. It is long. onnxruntime-extensions is a project implementing custom kernel without going through the process of validating the definition by onnx mainteners. The best option here is to implement is to implement a custom kernel. I'm hesitating in adding more in onnxruntime or creating a similar projet to host custom kernel dedicated to standard machine learning. But a custom kernel would solve the issue.

**Comment by vsbaldeev** [comment]
@xadupre What do you mean by custom kernel exactly ?

**Comment by xadupre** [comment]
A C++ implementation of an operator. Let's assume we define the operator StringNormalizer2. onnxruntime does not know it because it is new so it cannot run the inference unless we give it a piece of code compiled into an assembly. onnxruntime lets you do that. See https://onnxruntime.ai/docs/reference/operators/add-custom-op.html.

**Comment by xadupre** [comment]
This issue seems to be fixed with scikit-learn==1.5.0. Could you check on your side?

**Pull request merged**
