### PR TITLE
Update to scikit-learn==1.3.0

### PR DESCRIPTION
**Pull request by xadupre**

### CODE REVIEW

**Review by xiaowuhu — APPROVED** [review]

**Comment by gromlin2** [comment]
Thanks for putting in this change.

I would like to use scikit-learn 1.3, but blocked on this change. Is there any update, when a new version including this fix will be released?

**Comment by xadupre** [comment]
@xiaowuhu, do you think we can make a new release?

**Comment by xiaowuhu** [comment]
> @xiaowuhu, do you think we can make a new release?

Sure, will do it soon.

**Comment by gromlin2** [comment]
> > @xiaowuhu, do you think we can make a new release?
> 
> Sure, will do it soon.

That would be awesome, thanks a lot

**Comment by xiaowuhu** [comment]
Just released skl2onnx 1.15.0 to PyPI, please have a try.

**Pull request merged**
