### PR TITLE
[WIP] test on scikit-learn 0.19.2

### PR DESCRIPTION
**Pull request by xadupre**

### CODE REVIEW

**Comment by xadupre** [comment]
This will not pass the unit test unless we make some changes to the code to support 0.19.

**Comment by prabhat00155** [comment]
Do you know how big are those changes going to be?

**Comment by xadupre** [comment]
I would disable every model not supported with the current implementation (raise of an excetion) and disable all associated unit tests. That's the simplest.

**Comment by xadupre** [comment]
Fixed in #93.

**Pull request closed without merging**
